In [22]:
import os
print(os.getcwd())

c:\Users\Admin\hipython\ml\energy_app

In [23]:
import os
# test_data 폴더가 있는지, 뭐가 들어있는지 확인
print(os.path.exists('./test_data'))
print(os.listdir('./test_data') if os.path.exists('./test_data') else "폴더 없음")

True
['compare_sets_2021-03-24.csv', 'result_db_2021-03-24.csv', 'result_Mixed_2021-03-24.csv', 'result_Set_A_2021-03-24.csv', 'result_Set_B_2021-03-24.csv', 'result_Set_C_2021-03-24.csv', 'test_input_mixed.csv', 'test_input_SetA.csv', 'test_input_SetB.csv', 'test_input_SetC.csv']

In [24]:
import pandas as pd
df = pd.read_csv('./test_data/result_Mixed_2021-03-24.csv', encoding='utf-8-sig')
df

,Date,hour,temperature,humidity,windspeed,rainfall,op_code,output,weekday,weekend,holiday,applied_set,peak15,peak30,peak45,peak60
0,2021-03-24,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,41.259998,29.660000,41.349998,37.320000
1,2021-03-24,1,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,26.510000,33.540001,17.530001,31.309999
2,2021-03-24,2,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
3,2021-03-24,3,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
4,2021-03-24,4,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
5,2021-03-24,5,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
6,2021-03-24,6,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
7,2021-03-24,7,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
8,2021-03-24,8,12.3,51.5,2.0,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
9,2021-03-24,9,14.1,49.9,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
10,2021-03-24,10,15.7,48.0,1.2,0.0,NaN,NaN,3,0,0,Set_B,31.980000,44.349998,39.209999,52.290001
11,2021-03-24,11,16.5,46.1,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
12,2021-03-24,12,17.3,45.8,1.8,0.0,NaN,NaN,3,0,0,Set_B,33.919998,43.790001,39.529999,53.160000
13,2021-03-24,13,16.7,46.0,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
14,2021-03-24,14,16.0,49.9,1.8,0.0,NaN,NaN,3,0,0,Set_B,33.919998,43.790001,39.529999,53.160000
15,2021-03-24,15,14.6,48.9,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
16,2021-03-24,16,12.5,50.8,1.8,0.0,1.0,1974.0,3,0,0,Set_C,113.570000,122.120003,134.559998,112.589996
17,2021-03-24,17,10.8,56.3,2.7,0.0,2.0,238.0,3,0,0,Set_C,113.440002,120.930000,133.630005,111.629997
18,2021-03-24,18,8.3,58.3,2.7,0.0,2.0,235.0,3,0,0,Set_C,113.440002,120.930000,133.630005,111.629997
19,2021-03-24,19,5.4,60.2,1.0,0.0,1.0,1442.0,3,0,0,Set_C,115.830002,122.919998,137.710007,112.750000
20,2021-03-24,20,3.3,64.2,1.9,0.0,1.0,2162.0,3,0,0,Set_C,114.260002,122.139999,134.440002,112.080002
21,2021-03-24,21,1.9,65.6,1.4,0.0,2.0,159.0,3,0,0,Set_C,112.900002,123.190002,136.309998,112.199997
22,2021-03-24,22,-0.2,71.1,2.3,0.0,2.0,101.0,3,0,0,Set_C,95.739998,106.290001,109.849998,101.250000
23,2021-03-24,23,-1.2,71.6,1.8,0.0,2.0,204.0,3,0,0,Set_C,96.360001,107.550003,109.250000,101.839996

In [25]:
import pandas as pd

df = pd.read_csv('./test_data/result_Mixed_2021-03-24.csv', encoding='utf-8-sig')
df

,Date,hour,temperature,humidity,windspeed,rainfall,op_code,output,weekday,weekend,holiday,applied_set,peak15,peak30,peak45,peak60
0,2021-03-24,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,41.259998,29.660000,41.349998,37.320000
1,2021-03-24,1,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,26.510000,33.540001,17.530001,31.309999
2,2021-03-24,2,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
3,2021-03-24,3,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
4,2021-03-24,4,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
5,2021-03-24,5,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
6,2021-03-24,6,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
7,2021-03-24,7,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
8,2021-03-24,8,12.3,51.5,2.0,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
9,2021-03-24,9,14.1,49.9,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
10,2021-03-24,10,15.7,48.0,1.2,0.0,NaN,NaN,3,0,0,Set_B,31.980000,44.349998,39.209999,52.290001
11,2021-03-24,11,16.5,46.1,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
12,2021-03-24,12,17.3,45.8,1.8,0.0,NaN,NaN,3,0,0,Set_B,33.919998,43.790001,39.529999,53.160000
13,2021-03-24,13,16.7,46.0,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
14,2021-03-24,14,16.0,49.9,1.8,0.0,NaN,NaN,3,0,0,Set_B,33.919998,43.790001,39.529999,53.160000
15,2021-03-24,15,14.6,48.9,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
16,2021-03-24,16,12.5,50.8,1.8,0.0,1.0,1974.0,3,0,0,Set_C,113.570000,122.120003,134.559998,112.589996
17,2021-03-24,17,10.8,56.3,2.7,0.0,2.0,238.0,3,0,0,Set_C,113.440002,120.930000,133.630005,111.629997
18,2021-03-24,18,8.3,58.3,2.7,0.0,2.0,235.0,3,0,0,Set_C,113.440002,120.930000,133.630005,111.629997
19,2021-03-24,19,5.4,60.2,1.0,0.0,1.0,1442.0,3,0,0,Set_C,115.830002,122.919998,137.710007,112.750000
20,2021-03-24,20,3.3,64.2,1.9,0.0,1.0,2162.0,3,0,0,Set_C,114.260002,122.139999,134.440002,112.080002
21,2021-03-24,21,1.9,65.6,1.4,0.0,2.0,159.0,3,0,0,Set_C,112.900002,123.190002,136.309998,112.199997
22,2021-03-24,22,-0.2,71.1,2.3,0.0,2.0,101.0,3,0,0,Set_C,95.739998,106.290001,109.849998,101.250000
23,2021-03-24,23,-1.2,71.6,1.8,0.0,2.0,204.0,3,0,0,Set_C,96.360001,107.550003,109.250000,101.839996

In [26]:
%run test_db_insert.py

✅ 2021-03-24 날씨 데이터 이미 존재 (24행) → SKIP
✅ Calendar 2021-03-24 존재: {'date': '2021-03-24', 'year': 2021, 'month': 3, 'day': 24, 'weekday': 3, 'weekend': 0, 'holiday': 0}

다음: python test_predict.py

In [27]:
%run test_predict.py

============================================================
predictor1.py + power_db_operations.py 통합 테스트
대상 날짜: 2021-03-24
============================================================

[방법 1] DB → get_prediction_variables → predict_with_input
--------------------------------------------------
✅ DB 조회 완료: 24행 × 11컬럼

[입력 DataFrame]
          Date  hour  temperature  humidity  windspeed  rainfall op_code output  weekday  weekend  holiday
0   2021-03-24     0         -0.9      69.8        2.1       0.0    None   None        3        0        0
1   2021-03-24     1         -0.2      69.2        1.7       0.0    None   None        3        0        0
2   2021-03-24     2          0.7      69.5        1.6       0.0    None   None        3        0        0
3   2021-03-24     3          1.8      65.8        1.6       0.0    None   None        3        0        0
4   2021-03-24     4          3.6      61.1        1.1       0.0    None   None        3        0        0
5   2021-03-24     5          5.5      59.6        1.9       0.0    None   None        3        0        0
6   2021-03-24     6          7.7      55.9        2.4       0.0    None   None        3        0        0
7   2021-03-24     7         10.3      55.0        1.2       0.0    None   None        3        0        0
8   2021-03-24     8         12.3      52.2        1.3       0.0    None   None        3        0        0
9   2021-03-24     9         14.5      48.6        1.7       0.0    None   None        3        0        0
10  2021-03-24    10         15.6      50.4        1.8       0.0    None   None        3        0        0
11  2021-03-24    11         16.4      47.6        1.3       0.0    None   None        3        0        0
12  2021-03-24    12         17.1      43.1        1.3       0.0    None   None        3        0        0
13  2021-03-24    13         16.8      47.5        1.9       0.0    None   None        3        0        0
14  2021-03-24    14         15.8      47.2        1.2       0.0    None   None        3        0        0
15  2021-03-24    15         14.1      48.8        2.2       0.0    None   None        3        0        0
16  2021-03-24    16         12.6      49.4        1.9       0.0    None   None        3        0        0
17  2021-03-24    17         10.2      53.9        2.0       0.0    None   None        3        0        0
18  2021-03-24    18          8.3      59.4        1.5       0.0    None   None        3        0        0
19  2021-03-24    19          5.6      61.6        2.2       0.0    None   None        3        0        0
20  2021-03-24    20          3.4      63.7        1.4       0.0    None   None        3        0        0
21  2021-03-24    21          1.3      67.7        2.3       0.0    None   None        3        0        0
22  2021-03-24    22          0.2      69.9        1.9       0.0    None   None        3        0        0
23  2021-03-24    23         -0.9      70.1        2.4       0.0    None   None        3        0        0

[예측 실행 중...]

[예측 결과 DataFrame]
          Date  hour applied_set     peak15     peak30     peak45     peak60
0   2021-03-24     0       Set_B  62.330002  43.240002  51.590000  49.720001
1   2021-03-24     1       Set_B  58.560001  52.959999  45.299999  53.220001
2   2021-03-24     2       Set_B  29.379999  37.299999  36.869999  47.500000
3   2021-03-24     3       Set_B  35.299999  44.000000  39.169998  52.720001
4   2021-03-24     4       Set_B  31.980000  44.349998  39.209999  52.290001
5   2021-03-24     5       Set_B  44.369999  47.820000  51.220001  59.630001
6   2021-03-24     6       Set_B  46.000000  53.980000  54.430000  62.700001
7   2021-03-24     7       Set_B  31.980000  44.349998  39.209999  52.290001
8   2021-03-24     8       Set_B  32.380001  40.330002  37.160000  51.270000
9   2021-03-24     9       Set_B  33.919998  43.790001  39.529999  53.160000
10  2021-03-24    10       Set_B  33.919998  43.790001  39.529999  53.160000
11  2021-03-24    11       Set_B  32.380001  40.330002  37.160000  51.270000
12  2021-03-24    12       Set_B  32.380001  40.330002  37.160000  51.270000
13  2021-03-24    13       Set_B  44.369999  47.820000  51.220001  59.630001
14  2021-03-24    14       Set_B  31.980000  44.349998  39.209999  52.290001
15  2021-03-24    15       Set_B  44.830002  50.360001  52.560001  59.970001
16  2021-03-24    16       Set_B  44.369999  47.820000  51.220001  59.630001
17  2021-03-24    17       Set_B  44.369999  47.820000  51.220001  59.630001
18  2021-03-24    18       Set_B  29.129999  39.400002  39.110001  52.720001
19  2021-03-24    19       Set_B  44.830002  50.360001  52.560001  59.970001
20  2021-03-24    20       Set_B  29.129999  39.400002  39.110001  52.720001
21  2021-03-24    21       Set_B  44.950001  43.630001  45.930000  55.990002
22  2021-03-24    22       Set_B  54.959999  52.290001  57.560001  66.959999
23  2021-03-24    23       Set_B  57.509998  41.470001  49.549999  47.730000

✅ 저장: ./test_data\result_db_2021-03-24.csv

[적용 Set 분포]
applied_set
Set_B    24
Name: count, dtype: int64

============================================================
[방법 2] CSV → predict_with_input (Set별 개별 테스트)
============================================================

--- Set_A (날짜만) ---
  입력: 24행 | NaN 컬럼: ['temperature', 'humidity', 'windspeed', 'rainfall', 'op_code', 'output']
  적용 Set: {'Set_A': 24}
  peak15: mean=31.1 max=41.3 min=26.5
  ✅ 저장: ./test_data\result_Set_A_2021-03-24.csv

--- Set_B (날짜+날씨) ---
  입력: 24행 | NaN 컬럼: ['op_code', 'output']
  적용 Set: {'Set_B': 24}
  peak15: mean=39.7 max=59.2 min=29.1
  ✅ 저장: ./test_data\result_Set_B_2021-03-24.csv

--- Set_C (전체) ---
  입력: 24행 | NaN 컬럼: 없음 (Set_C)
  적용 Set: {'Set_C': 24}
  peak15: mean=103.4 max=116.0 min=35.8
  ✅ 저장: ./test_data\result_Set_C_2021-03-24.csv

--- Mixed (A+B+C 혼합) ---
  입력: 24행 | NaN 컬럼: ['temperature', 'humidity', 'windspeed', 'rainfall', 'op_code', 'output']
  적용 Set: {'Set_A': 8, 'Set_B': 8, 'Set_C': 8}
  peak15: mean=60.4 max=115.8 min=26.5
  ✅ 저장: ./test_data\result_Mixed_2021-03-24.csv

============================================================
Set 간 peak15 비교 요약
============================================================
              구분  mean   max  min  std
     Set_A (날짜만)  31.1  41.3 26.5  2.3
   Set_B (날짜+날씨)  39.7  59.2 29.1  8.5
      Set_C (전체) 103.4 116.0 35.8 20.6
Mixed (A+B+C 혼합)  60.4 115.8 26.5 36.1

✅ 비교표 저장: ./test_data/compare_sets_2021-03-24.csv

============================================================
테스트 완료! test_data/ 폴더의 CSV 파일을 확인하세요.
============================================================

In [28]:
import os
print(os.listdir('./test_data'))

['compare_sets_2021-03-24.csv', 'result_db_2021-03-24.csv', 'result_Mixed_2021-03-24.csv', 'result_Set_A_2021-03-24.csv', 'result_Set_B_2021-03-24.csv', 'result_Set_C_2021-03-24.csv', 'test_input_mixed.csv', 'test_input_SetA.csv', 'test_input_SetB.csv', 'test_input_SetC.csv']

In [29]:
import pandas as pd
df = pd.read_csv('./test_data/result_Mixed_2021-03-24.csv', encoding='utf-8-sig')
df

,Date,hour,temperature,humidity,windspeed,rainfall,op_code,output,weekday,weekend,holiday,applied_set,peak15,peak30,peak45,peak60
0,2021-03-24,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,41.259998,29.660000,41.349998,37.320000
1,2021-03-24,1,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,26.510000,33.540001,17.530001,31.309999
2,2021-03-24,2,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
3,2021-03-24,3,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
4,2021-03-24,4,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
5,2021-03-24,5,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
6,2021-03-24,6,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
7,2021-03-24,7,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
8,2021-03-24,8,12.3,51.5,2.0,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
9,2021-03-24,9,14.1,49.9,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
10,2021-03-24,10,15.7,48.0,1.2,0.0,NaN,NaN,3,0,0,Set_B,31.980000,44.349998,39.209999,52.290001
11,2021-03-24,11,16.5,46.1,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
12,2021-03-24,12,17.3,45.8,1.8,0.0,NaN,NaN,3,0,0,Set_B,33.919998,43.790001,39.529999,53.160000
13,2021-03-24,13,16.7,46.0,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
14,2021-03-24,14,16.0,49.9,1.8,0.0,NaN,NaN,3,0,0,Set_B,33.919998,43.790001,39.529999,53.160000
15,2021-03-24,15,14.6,48.9,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
16,2021-03-24,16,12.5,50.8,1.8,0.0,1.0,1974.0,3,0,0,Set_C,113.570000,122.120003,134.559998,112.589996
17,2021-03-24,17,10.8,56.3,2.7,0.0,2.0,238.0,3,0,0,Set_C,113.440002,120.930000,133.630005,111.629997
18,2021-03-24,18,8.3,58.3,2.7,0.0,2.0,235.0,3,0,0,Set_C,113.440002,120.930000,133.630005,111.629997
19,2021-03-24,19,5.4,60.2,1.0,0.0,1.0,1442.0,3,0,0,Set_C,115.830002,122.919998,137.710007,112.750000
20,2021-03-24,20,3.3,64.2,1.9,0.0,1.0,2162.0,3,0,0,Set_C,114.260002,122.139999,134.440002,112.080002
21,2021-03-24,21,1.9,65.6,1.4,0.0,2.0,159.0,3,0,0,Set_C,112.900002,123.190002,136.309998,112.199997
22,2021-03-24,22,-0.2,71.1,2.3,0.0,2.0,101.0,3,0,0,Set_C,95.739998,106.290001,109.849998,101.250000
23,2021-03-24,23,-1.2,71.6,1.8,0.0,2.0,204.0,3,0,0,Set_C,96.360001,107.550003,109.250000,101.839996

In [30]:
import pandas as pd
df = pd.read_csv('./test_data/result_Mixed_2021-03-24.csv', encoding='utf-8-sig')
df

,Date,hour,temperature,humidity,windspeed,rainfall,op_code,output,weekday,weekend,holiday,applied_set,peak15,peak30,peak45,peak60
0,2021-03-24,0,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,41.259998,29.660000,41.349998,37.320000
1,2021-03-24,1,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,26.510000,33.540001,17.530001,31.309999
2,2021-03-24,2,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
3,2021-03-24,3,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
4,2021-03-24,4,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
5,2021-03-24,5,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
6,2021-03-24,6,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
7,2021-03-24,7,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,Set_A,30.799999,38.119999,34.689999,38.700001
8,2021-03-24,8,12.3,51.5,2.0,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
9,2021-03-24,9,14.1,49.9,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
10,2021-03-24,10,15.7,48.0,1.2,0.0,NaN,NaN,3,0,0,Set_B,31.980000,44.349998,39.209999,52.290001
11,2021-03-24,11,16.5,46.1,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
12,2021-03-24,12,17.3,45.8,1.8,0.0,NaN,NaN,3,0,0,Set_B,33.919998,43.790001,39.529999,53.160000
13,2021-03-24,13,16.7,46.0,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
14,2021-03-24,14,16.0,49.9,1.8,0.0,NaN,NaN,3,0,0,Set_B,33.919998,43.790001,39.529999,53.160000
15,2021-03-24,15,14.6,48.9,1.9,0.0,NaN,NaN,3,0,0,Set_B,44.369999,47.820000,51.220001,59.630001
16,2021-03-24,16,12.5,50.8,1.8,0.0,1.0,1974.0,3,0,0,Set_C,113.570000,122.120003,134.559998,112.589996
17,2021-03-24,17,10.8,56.3,2.7,0.0,2.0,238.0,3,0,0,Set_C,113.440002,120.930000,133.630005,111.629997
18,2021-03-24,18,8.3,58.3,2.7,0.0,2.0,235.0,3,0,0,Set_C,113.440002,120.930000,133.630005,111.629997
19,2021-03-24,19,5.4,60.2,1.0,0.0,1.0,1442.0,3,0,0,Set_C,115.830002,122.919998,137.710007,112.750000
20,2021-03-24,20,3.3,64.2,1.9,0.0,1.0,2162.0,3,0,0,Set_C,114.260002,122.139999,134.440002,112.080002
21,2021-03-24,21,1.9,65.6,1.4,0.0,2.0,159.0,3,0,0,Set_C,112.900002,123.190002,136.309998,112.199997
22,2021-03-24,22,-0.2,71.1,2.3,0.0,2.0,101.0,3,0,0,Set_C,95.739998,106.290001,109.849998,101.250000
23,2021-03-24,23,-1.2,71.6,1.8,0.0,2.0,204.0,3,0,0,Set_C,96.360001,107.550003,109.250000,101.839996