Series

In [3]:
import pandas as pd

In [ ]:
시리즈 : 컬럼 + 인덱스 형식으로 저장, 관리
* 컬럼 : 1차원 데이터 모음 -1개 컬럼
* 컬럼들 : 데이터프레임

데이터프레임 : 컬럼들 + 인덱스, 엑셀 표(테이블) 유사한 형태

In [6]:
s1 = pd.Series([10,20,30]) #__init__(self, 리스트객체)
s1[0:2]

0    10
1    20
dtype: int64

In [8]:
col_idx = ['A','B','C']
data = [10,20,30]
s2 = pd.Series(data, index=col_idx)
s2 #판다스 데이터타입 = dtype

A    10
B    20
C    30
dtype: int64

In [9]:
s2['A':'C'] #슬라이싱, 인덱스 이름 기반 추출

A    10
B    20
C    30
dtype: int64

In [10]:
dict_data = {'A':10, 'B':20, 'C':30} #딕셔너리 key = 시리즈 인덱스
type(dict_data)
s3 = pd.Series(dict_data)

In [11]:
s3.info() #객체의 메소드

<class 'pandas.core.series.Series'>
Index: 3 entries, A to C
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 48.0+ bytes

In [13]:
population = pd.Series([9776, 2729, 1566, 3158], 
                    index=['서울', '부산', '인천', '대구'])
population

서울    9776
부산    2729
인천    1566
대구    3158
dtype: int64

In [16]:
print(population['서울'])  # 9776 출력

9776

In [17]:
print(population[['서울', '부산']])  # 서울과 부산의 데이터만

서울    9776
부산    2729
dtype: int64

In [18]:
print(population[['인천', '대구']])  # 서울과 부산의 데이터만

인천    1566
대구    3158
dtype: int64

In [21]:
population['제주'] = 1000

In [22]:
population

서울    9776
부산    2729
인천    1566
대구    3158
제주    1000
dtype: int64

In [ ]:
# 데이터 프레임 DataFrame

In [ ]:
# 리스트로 데이터프레임 생성
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
pd.DataFrame(data, columns=['A', 'B', 'C'])

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [29]:
pd.DataFrame(data, columns=['A', 'B', 'C'], index=['홍길동', '김길동', '박길동'])

     A  B  C
홍길동  1  2  3
김길동  4  5  6
박길동  7  8  9

In [27]:
import numpy as np
import pandas as pd

In [30]:
names = pd.Series(['김철수', '이영희', '박민수'])
ages = pd.Series([25, 28, 22])
scores = pd.Series([85, 92, 78])
names, ages, scores

(0    김철수
 1    이영희
 2    박민수
 dtype: object,
 0    25
 1    28
 2    22
 dtype: int64,
 0    85
 1    92
 2    78
 dtype: int64)

In [ ]:
#pd.DataFrame([names,ages,scores])
pd.DataFrame({'이름':names, '나이':ages, '점수':scores})

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78

In [ ]:
#시리즈로 데이트프레임 생성하기

In [32]:
# 시리즈 생성
names = pd.Series(['김철수', '이영희', '박민수'])
ages = pd.Series([25, 28, 22])
scores = pd.Series([85, 92, 78])

# 시리즈를 딕셔너리로 묶어 데이터프레임 생성
df = pd.DataFrame({
    '이름': names,
    '나이': ages,
    '점수': scores
})
print(df)

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78

In [ ]:
# 딕셔너리로 데이터프레임 생성하기

In [33]:
data = {
    '이름': ['김철수', '이영희', '박민수'],
    '나이': [25, 28, 22],
    '점수': [85, 92, 78]
}
df = pd.DataFrame(data)
print(df)

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78

In [34]:
import pandas as pd

# 샘플 데이터프레임 생성
data = {
    '이름': ['김철수', '이영희', '박민수', '정수진', '최영호', '한미래', '윤지원'],
    '나이': [25, 28, 22, 31, 27, 24, 29],
    '점수': [85, 92, 78, 95, 88, 73, 91]
}
df = pd.DataFrame(data)

# 처음 5개 행 보기
print("=== head() ===")
print(df.head())

# 마지막 3개 행 보기
print("\n=== tail(3) ===")
print(df.tail(3))

# 데이터프레임 기본 정보
print("\n=== info() ===")
print(df.info())

# 기술 통계량
print("\n=== describe() ===")
print(df.describe())

=== head() ===
    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78
3  정수진  31  95
4  최영호  27  88

=== tail(3) ===
    이름  나이  점수
4  최영호  27  88
5  한미래  24  73
6  윤지원  29  91

=== info() ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      7 non-null      object
 1   나이      7 non-null      int64
 2   점수      7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes
None

=== describe() ===
              나이         점수
count   7.000000   7.000000
mean   26.571429  86.000000
std     3.101459   7.958224
min    22.000000  73.000000
25%    24.500000  81.500000
50%    27.000000  88.000000
75%    28.500000  91.500000
max    31.000000  95.000000

In [35]:
print(df.index)    # 행 이름 출력
print(df.columns)  # 열 이름 출력

RangeIndex(start=0, stop=7, step=1)
Index(['이름', '나이', '점수'], dtype='object')

In [ ]:
# 행 이름 변경
df.index = ['A', 'B', 'C', 'D', 'E', 'F', 'G'] #replace
print(df.index)

# columns 속성으로 모든 열 이름 한번에 변경
df.columns = ['name', 'age', 'score']

# 열 순서는 그대로 유지되며, 새로운 이름이 순서대로 적용됨
print(df.columns)

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')
Index(['name', 'age', 'score'], dtype='object')

In [ ]:
df.rename(columns={'name': '이름', 'age': '나이', 'score': '점수'}, inplace=True) #inplace=True 옵션을 사용하여 원본 데이터프레임을 직접 수정
print(df.columns)
# inplace >> 새로운 df 복사본에서 확인하는 방법이 안전

Index(['이름', '나이', '점수'], dtype='object')

In [41]:
df1 = df.rename(columns={'name': '이름'})

In [42]:
df

    이름  나이  점수
A  김철수  25  85
B  이영희  28  92
C  박민수  22  78
D  정수진  31  95
E  최영호  27  88
F  한미래  24  73
G  윤지원  29  91

In [44]:
df1

    이름  나이  점수
A  김철수  25  85
B  이영희  28  92
C  박민수  22  78
D  정수진  31  95
E  최영호  27  88
F  한미래  24  73
G  윤지원  29  91

In [45]:
#미리보기
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, A to G
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      7 non-null      object
 1   나이      7 non-null      int64
 2   점수      7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 524.0+ bytes

In [ ]:
df.head(3)

    이름  나이  점수
A  김철수  25  85
B  이영희  28  92
C  박민수  22  78

In [49]:
df.tail(3)

    이름  나이  점수
E  최영호  27  88
F  한미래  24  73
G  윤지원  29  91

In [48]:
df.describe()

              나이         점수
count   7.000000   7.000000
mean   26.571429  86.000000
std     3.101459   7.958224
min    22.000000  73.000000
25%    24.500000  81.500000
50%    27.000000  88.000000
75%    28.500000  91.500000
max    31.000000  95.000000

In [ ]:
#인덱싱

 [행, 열] 인덱싱

 * iloc[] 행기반 인덱싱 >>> [행, 열]
 * loc[] 이름기반(위치) 인덱싱 >>> [행이름, 열이름]

 - : >> start:end 까지 슬라이싱
 - loc[행이름, 열이름]
 - iloc[행번호, 열번호]

In [56]:
#df1[['이름,'나이']]
df1.loc[:,['이름','나이']] # loc[행, 열] 행과 열을 반드시 지정

    이름  나이
A  김철수  25
B  이영희  28
C  박민수  22
D  정수진  31
E  최영호  27
F  한미래  24
G  윤지원  29

In [57]:
df1.loc['A']

이름    김철수
나이     25
점수     85
Name: A, dtype: object

In [59]:
df1.iloc[0:3, 0:2] #행번호, 열

    이름  나이
A  김철수  25
B  이영희  28
C  박민수  22

In [ ]:
# 연습문제

In [ ]:
# [기본]

# 모든 행에서 이름 열만 선택하세요.
df1['이름']

# 모든 행에서 이름과 score 열을 선택하세요.
df1[['이름', 'score']]

# 인덱스 C 행의 모든 데이터를 선택하세요.
df1.loc['C']

# 인덱스 D 행의 age 값만 선택하세요.
df1.loc['D', 'age']

In [ ]:
# [슬라이싱]

# 인덱스 B부터 E까지의 모든 행을 선택하세요.
df1.loc['B':'E']
# 인덱스 C부터 F까지의 이름과 age 열만 선택하세요.
df1.loc['C':'F', ['이름','age']]
# 인덱스 A부터 G까지에서 score 열만 선택하세요.
df1.loc['A':'G', 'score']

Boolean 인덱싱

In [ ]:
df [ df['점수'] > 90 ] #vectorization boolean list의 요소 값 True, False

    이름  나이  점수
B  이영희  28  92
D  정수진  31  95
G  윤지원  29  91

In [68]:
cond = df1['나이'] >= 27

In [71]:
# [조건 + loc]

# age가 27 이상인 행만 선택하세요.
df1.loc[cond]

# score가 90 이상인 사람의 이름과 score만 출력하세요.
df1.loc[  df1['점수']>=90,  ['이름', '점수']  ]

# age가 25 이상이면서 score가 90 이상인 행을 모두 선택하세요.
cond1 = df1['나이'] >=25
cond2 = df1['점수']>=90
df1.loc[cond1 & cond2]

    이름  나이  점수
B  이영희  28  92
D  정수진  31  95
G  윤지원  29  91

In [ ]:
iloc 인덱싱 & 슬라이싱 연습문제

👉 정수 위치 기반 (0부터 시작)

In [73]:
# [기본]
# 첫 번째 행의 모든 데이터를 선택하세요.
df1.iloc[0]
# 세 번째 행의 이름 값만 선택하세요.
df1.iloc[2,0]
# 처음 3개의 행을 선택하세요.
df1.iloc[ :3, ]
# 마지막 행의 score 값만 선택하세요.
df1.iloc[-1, 2]

np.int64(91)

In [74]:
# [슬라이싱]
# 1번 행부터 4번 행까지 선택하세요.
df1.iloc[1:5]
# 2번 행부터 5번 행까지에서 이름과 age 열만 선택하세요.
df1.iloc[2:6, [0,1]]
# 모든 행에서 age 열만 선택하세요.
df1.iloc[:, 1]

A    25
B    28
C    22
D    31
E    27
F    24
G    29
Name: 나이, dtype: int64

In [78]:
# [조합 문제]
# score 열만 선택하되, 앞에서 4개의 행만 출력하세요.
df1.iloc[0:4,2]
# 이름과 score 열을 선택하되, 마지막 3개의 행만 출력하세요.
df.iloc[-3: , ::2] #start:end:step
df1.tail(3).loc[:,['이름','점수']]
# 짝수 번째 행(0, 2, 4, 6)의 모든 데이터를 선택하세요.
df1.iloc[[0,2,4,6]]

    이름  나이  점수
A  김철수  25  85
C  박민수  22  78
E  최영호  27  88
G  윤지원  29  91

In [ ]:
# 행주가와 열추가

In [ ]:
df.loc['H'] = ['장민호', 26, 88]
df['grade'] = ['A','B','A', 'A','B','C','A']

In [81]:
# 인덱스로 행 삭제
df.drop('A', axis=0)  # 'A' 인덱스의 행 삭제

# 여러 행 한 번에 삭제
df.drop(['B', 'C'], axis=0)

    이름  나이  점수
A  김철수  25  85
D  정수진  31  95
E  최영호  27  88
F  한미래  24  73
G  윤지원  29  91
H  장민호  26  88

In [ ]:
# 열 이름으로 열 삭제
df.drop('grade', axis=1)  # 'grade' 열 삭제

# 여러 열 한 번에 삭제
df.drop(['age', 'score'], axis=1)

In [ ]:
# 데이터형 변환

In [ ]:
# 객체를 숫자형으로 변환
df = df.astype({'age': int, 'score': float})

# 문자열로 변환
df['student_id'] = df['student_id'].astype(str)

# 날짜형으로 변환
df['date'] = pd.to_datetime(df['date'])

In [ ]:
# 인덱스의 설정

In [ ]:
# 'student_id' 열을 인덱스로 설정
df.set_index('student_id', inplace=True)

# 인덱스를 다시 열로 되돌리기
df.reset_index(inplace=True)